/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.msic.test.liferay.service.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the user service. Represents a row in the &quot;user_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.msic.test.liferay.service.user.model.impl.userModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.msic.test.liferay.service.user.model.impl.userImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see user
 * @generated
 */
@ProviderType
public interface userModel extends BaseModel<user> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user model instance should use the {@link user} interface instead.
	 */

	/**
	 * Returns the primary key of this user.
	 *
	 * @return the primary key of this user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user.
	 *
	 * @param primaryKey the primary key of this user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this user.
	 *
	 * @return the uuid of this user
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user.
	 *
	 * @param uuid the uuid of this user
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user ID of this user.
	 *
	 * @return the user ID of this user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user.
	 *
	 * @param userId the user ID of this user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user.
	 *
	 * @return the user uuid of this user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user.
	 *
	 * @param userUuid the user uuid of this user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this user.
	 *
	 * @return the group ID of this user
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user.
	 *
	 * @param groupId the group ID of this user
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the u ID of this user.
	 *
	 * @return the u ID of this user
	 */
	public long getUId();

	/**
	 * Sets the u ID of this user.
	 *
	 * @param uId the u ID of this user
	 */
	public void setUId(long uId);

	/**
	 * Returns the user name of this user.
	 *
	 * @return the user name of this user
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this user.
	 *
	 * @param userName the user name of this user
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this user.
	 *
	 * @return the create date of this user
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user.
	 *
	 * @param createDate the create date of this user
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user.
	 *
	 * @return the modified date of this user
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user.
	 *
	 * @param modifiedDate the modified date of this user
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public user cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}